### PR TITLE
Fix typo in GIFT equivalent trait

### PR DESCRIPTION
**Pull request by Rekyt**
Hi @ehwenk and @dfalster 👋 
I'm working with the raw data file `APD_traits_input.csv` for the sake of simplicity rather than the RDF files (maybe I shouldn't?😅 ) I noticed a typo in one trait with GIFT.

So I'm proposing to correct it.

### CODE REVIEW

**Comment by ehwenk** [comment]
@Reykt Thank you for letting us know about this error. I have moved this change to this branch - https://github.com/traitecoevo/APD/commit/0e3d720ff2125b4fda9f4c62407cdf247b4d85ad - to avoid conflicts when we merge two branches that both have edits to APD_traits_input.csv.

I'll leave this pull request open for now, but close it when we merge in the other branch, hopefully in the coming month.

**Comment by dfalster** [comment]
Thanks for your inputs @Rekyt !

**Comment by Rekyt** [comment]
Just for the sake of completeness I've tried to match all traits that would have non-matching square brackets using the following expression:

```r
raw_apd |>
  select(contains("LEDA"), contains("BROT"), contains("TOP"), contains("GIFT"),
         contains("BIEN"), contains("TRY")) |>
  filter(if_any(everything(), \(x) x != "" & !grepl("\\[[^][]*]", x)))
```

And the good news is that apart from this one in GIFT, I found no other! So, in this regard, the file seems correct.

**Comment by dfalster** [comment]
Closing as these changes have been addressed via #26

**Pull request closed without merging**
